logging:
    level:
        root: ERROR
        org.springframework: ERROR
        org.hibernate.SQL: INFO
        com.clinistats: DEBUG
        org.hibernate: ERROR

server.servlet.contextPath   : /desk/
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: "jdbc:postgresql://192.168.11.212:5432/EmrGlobal?currentSchema=helpdesk_dev"
    username: helpdeskuser
    password: 0129c8b6@2ed7110921
    
  application:
      name: helpdesk-services
  main:
    banner-mode: "off"
     
eureka:
   client:
      serviceUrl:
        defaultZone: http://192.168.11.218:8764/ehrdiscovery/eureka
   instance:
      prefer-ip-address: true    

server:
  port: 9090
  servlet:    
     application-display-name: helpdesk-services

spring.profiles:
     active: dev

jwt.secret:
  clinistats      


base.path: /opt/
aws.publicBucket:
  ehr-uploadattachments-dev

