spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/helpdesk?currentSchema=local5"
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
      name: help-desk
  main:
    banner-mode: "off"
    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.11.218:8764/ehrdiscovery/eureka
#  instance:
#    prefer-ip-address: true 

jwt:
   secret: clinistats

server:
  port: 8080
  servlet:    
     application-display-name: helpdesk
     context-path: /helpdesk
    
base.path: /opt/HelpSupport/
aws.publicBucket:
  ehr-uploadattachments-dev